spring.application.name=survey-engine
server.port=8080

# =========================
# FLYWAY (OFF mientras no haya STAGING)
# =========================
spring.flyway.enabled=false

# =========================
# DATASOURCE VERINA (OFF mientras no haya credenciales)
# =========================
app.datasource.verina.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
# NO pongas url/username/password aún

# =========================
# DATASOURCE STAGING (OFF mientras no haya credenciales)
# =========================
app.datasource.staging.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
# NO pongas url/username/password aún

# =========================
# JOBS (OFF)
# =========================
app.jobs.verinaPull.enabled=false

# =========================
# ACTUATOR
# =========================
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

# (opcional) Para que Health salga UP aunque haya algún bean db colgado
management.health.db.enabled=false

# Flags para activar BD
app.datasource.verina.enabled=false
app.datasource.staging.enabled=false


# ===== Clientify =====
app.clientify.base-url=https://api.clientify.net/v1
app.clientify.token=Token ${CLIENTIFY_TOKEN}
app.clientify.custom-fields.ultima-compra-ticket-id=505220
# Tag requerido
app.clientify.tags.encuesta-satisfaccion=encuesta_satisfaccion