spring.application.name=survey-engine
server.port=8080

# =========================
# FLYWAY (usa STAGING)
# =========================
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.flyway.url=${app.datasource.staging.url}
spring.flyway.user=${app.datasource.staging.username}
spring.flyway.password=${app.datasource.staging.password}

# =========================
# DATASOURCE VERINA (READ ONLY)
# =========================
app.datasource.verina.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
app.datasource.verina.url=jdbc:sqlserver://TU_HOST_VERINA:1433;databaseName=BatteryPlus;encrypt=true;trustServerCertificate=true
app.datasource.verina.username=${VERINA_DB_USER}
app.datasource.verina.password=${VERINA_DB_PASS}
app.datasource.verina.maximum-pool-size=5

# =========================
# DATASOURCE STAGING (WRITE)
# =========================
app.datasource.staging.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
app.datasource.staging.url=jdbc:sqlserver://TU_HOST_STAGING:1433;databaseName=SurveyEngine;encrypt=true;trustServerCertificate=true
app.datasource.staging.username=${STAGING_DB_USER}
app.datasource.staging.password=${STAGING_DB_PASS}
app.datasource.staging.maximum-pool-size=5



# =========================
# ACTUATOR
# =========================
management.endpoints.web.exposure.include=health,info