spring.application.name=survey-engine
server.port=9080


# =========================
# ACTUATOR
# =========================
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
management.health.db.enabled=false

# =========================
# FLAGS (enciende/apaga m�dulos)
# =========================
app.datasource.verina.enabled=true
app.datasource.staging.enabled=true
app.jobs.verinaPull.enabled=true
app.jobs.verinaPull.runner.enabled=false

# =========================
# VERINA (cuando lo habilites)
# =========================
app.datasource.verina.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
app.datasource.verina.jdbc-url=jdbc:sqlserver://${VERINA_DB_HOST}:1433;databaseName=BatteryPlus;encrypt=true;trustServerCertificate=true
app.datasource.verina.username=${VERINA_DB_USER}
app.datasource.verina.password=${VERINA_DB_PASS}
app.datasource.verina.maximum-pool-size=5

# =========================
# STAGING
# =========================
app.datasource.staging.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
app.datasource.staging.jdbc-url=jdbc:sqlserver://localhost\\SQLEXPRESS;databaseName=SurveyEngine;encrypt=true;trustServerCertificate=true
app.datasource.staging.username=${STAGING_DB_USER}
app.datasource.staging.password=${STAGING_DB_PASS}
app.datasource.staging.maximum-pool-size=5

# =========================
# FLYWAY
# =========================
spring.flyway.enabled=true
spring.flyway.url=${app.datasource.staging.jdbc-url}
spring.flyway.user=${app.datasource.staging.username}
spring.flyway.password=${app.datasource.staging.password}

# =========================
# CLIENTIFY API
# =========================
app.clientify.base-url=https://api.clientify.net/v1
app.clientify.token=Token ${CLIENTIFY_API_KEY}

app.clientify.custom-fields.fecha-ultima-compra-id=437747
app.clientify.custom-fields.bateria-adquirida-id=437643
app.clientify.custom-fields.sucursal-id=433527
app.clientify.custom-fields.anio-auto-id=433523
app.clientify.custom-fields.modelo-auto-id=433521
app.clientify.custom-fields.marca-auto-id=433520
app.clientify.custom-fields.marca-bateria-id=437455
app.clientify.custom-fields.gama-id=437456
app.clientify.custom-fields.fecha-fin-garantia-id=437457

app.clientify.tags.encuesta-satisfaccion=encuesta_postventa

# =========================
# CLIENTIFY INLINE (UI / object-inline-edit)
# =========================
app.clientify.inline-base-url=https://app.clientify.com
app.clientify.inline-path=/object-inline-edit/23/
app.clientify.inline-cookie=sessionid=at8cj4ge59lrvfzdobbqh9iq1fkinstk; csrftoken=DVXQtTOvLV0ljPnpUcJx2YVfrsjDUiT0
app.clientify.inline-csrf-token=DVXQtTOvLV0ljPnpUcJx2YVfrsjDUiT0

app.clientify.status-client-value=client

app.clientify.contact-source-piso-id=838954
app.clientify.contact-source-domicilio-id=1374358

app.clientify.owner-martin-id=202385
app.clientify.owner-daniela-id=286678

